<%@ Page Title="Account Beheer" Language="C#" MasterPageFile="~/Pages/SubMasterPage.master" AutoEventWireup="true" CodeBehind="AccountIndex.aspx.cs" Inherits="ICT4RAILS___ASP.NET.Pages.WebForm1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="CSS" runat="server">
    <link rel="stylesheet" href="/css/Accountbeheer.css" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="CPHBody" runat="server">
    <form runat="server">
        <div class="container">
            <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1>Medewerkers:</h1>
                        <asp:GridView ID="GridMedewerker1" runat="server" DataKeyNames="id" DataMember="naamMedewerker" OnRowDataBound="OnRowDataBound" OnRowDeleting="GridMedewerker1_OnRowDeleting"
                            EmptyDataText="Er zijn geen medewerkers meer." AutoGenerateDeleteButton="true"  Width="50%" class="table table-striped">
                         </asp:GridView>
                        <br/>
                        <asp:Button ID="NaarAccountAanmaken" CssClass="btn btn-default" runat="server" Text="Account aanmaken" OnClick="NaarAccountAanmaken_OnClick"/>
                    </div>
                </div>
            </div>
        </div>
      </div>
      </form>
</asp:Content>
